[options]
admin_passwd = $pbkdf2-sha512$600000$gnDuPSdEaA2hNCZEyFkrRQ$nkxO1ujvhMynadolNv3uzMoX/E8oEk2pxPcu7MJP1J.0g3QGye/XoH5NJn0N6B1CKJnRMcDiyGyEoz1f11aVIQ
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

